/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedQuotationsRouteImport } from './routes/_authenticated/quotations'
import { Route as AuthenticatedPricingRouteImport } from './routes/_authenticated/pricing'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCustomersRouteImport } from './routes/_authenticated/customers'
import { Route as AuthenticatedQuotationsNewRouteImport } from './routes/_authenticated/quotations.new'
import { Route as AuthenticatedQuotationsIdRouteImport } from './routes/_authenticated/quotations.$id'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedQuotationsRoute = AuthenticatedQuotationsRouteImport.update({
  id: '/quotations',
  path: '/quotations',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPricingRoute = AuthenticatedPricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCustomersRoute = AuthenticatedCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedQuotationsNewRoute =
  AuthenticatedQuotationsNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedQuotationsRoute,
  } as any)
const AuthenticatedQuotationsIdRoute =
  AuthenticatedQuotationsIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedQuotationsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/customers': typeof AuthenticatedCustomersRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/pricing': typeof AuthenticatedPricingRoute
  '/quotations': typeof AuthenticatedQuotationsRouteWithChildren
  '/settings': typeof AuthenticatedSettingsRoute
  '/quotations/$id': typeof AuthenticatedQuotationsIdRoute
  '/quotations/new': typeof AuthenticatedQuotationsNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/customers': typeof AuthenticatedCustomersRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/pricing': typeof AuthenticatedPricingRoute
  '/quotations': typeof AuthenticatedQuotationsRouteWithChildren
  '/settings': typeof AuthenticatedSettingsRoute
  '/quotations/$id': typeof AuthenticatedQuotationsIdRoute
  '/quotations/new': typeof AuthenticatedQuotationsNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/customers': typeof AuthenticatedCustomersRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/pricing': typeof AuthenticatedPricingRoute
  '/_authenticated/quotations': typeof AuthenticatedQuotationsRouteWithChildren
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/quotations/$id': typeof AuthenticatedQuotationsIdRoute
  '/_authenticated/quotations/new': typeof AuthenticatedQuotationsNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/customers'
    | '/dashboard'
    | '/pricing'
    | '/quotations'
    | '/settings'
    | '/quotations/$id'
    | '/quotations/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/customers'
    | '/dashboard'
    | '/pricing'
    | '/quotations'
    | '/settings'
    | '/quotations/$id'
    | '/quotations/new'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/customers'
    | '/_authenticated/dashboard'
    | '/_authenticated/pricing'
    | '/_authenticated/quotations'
    | '/_authenticated/settings'
    | '/_authenticated/quotations/$id'
    | '/_authenticated/quotations/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/quotations': {
      id: '/_authenticated/quotations'
      path: '/quotations'
      fullPath: '/quotations'
      preLoaderRoute: typeof AuthenticatedQuotationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pricing': {
      id: '/_authenticated/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof AuthenticatedPricingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/customers': {
      id: '/_authenticated/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof AuthenticatedCustomersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/quotations/new': {
      id: '/_authenticated/quotations/new'
      path: '/new'
      fullPath: '/quotations/new'
      preLoaderRoute: typeof AuthenticatedQuotationsNewRouteImport
      parentRoute: typeof AuthenticatedQuotationsRoute
    }
    '/_authenticated/quotations/$id': {
      id: '/_authenticated/quotations/$id'
      path: '/$id'
      fullPath: '/quotations/$id'
      preLoaderRoute: typeof AuthenticatedQuotationsIdRouteImport
      parentRoute: typeof AuthenticatedQuotationsRoute
    }
  }
}

interface AuthenticatedQuotationsRouteChildren {
  AuthenticatedQuotationsIdRoute: typeof AuthenticatedQuotationsIdRoute
  AuthenticatedQuotationsNewRoute: typeof AuthenticatedQuotationsNewRoute
}

const AuthenticatedQuotationsRouteChildren: AuthenticatedQuotationsRouteChildren =
  {
    AuthenticatedQuotationsIdRoute: AuthenticatedQuotationsIdRoute,
    AuthenticatedQuotationsNewRoute: AuthenticatedQuotationsNewRoute,
  }

const AuthenticatedQuotationsRouteWithChildren =
  AuthenticatedQuotationsRoute._addFileChildren(
    AuthenticatedQuotationsRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedCustomersRoute: typeof AuthenticatedCustomersRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedPricingRoute: typeof AuthenticatedPricingRoute
  AuthenticatedQuotationsRoute: typeof AuthenticatedQuotationsRouteWithChildren
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedCustomersRoute: AuthenticatedCustomersRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedPricingRoute: AuthenticatedPricingRoute,
  AuthenticatedQuotationsRoute: AuthenticatedQuotationsRouteWithChildren,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
